webtalk_init -webtalk_dir F:\\workspace_Vivado2015.1\\detectfoot_linux\\detectfoot_linux.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期四 四月 7 09:33:02 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "135256_15690819_173552794_661" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a9avl7aec1frknrij0bm9fggsm" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1459992521101" -context "sdk\\\\application/1459992521101"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1459992521101"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1459992521101"
webtalk_transmit -clientid 712960879 -regid "135256_15690819_173552794_661" -xml F:\\workspace_Vivado2015.1\\detectfoot_linux\\detectfoot_linux.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\workspace_Vivado2015.1\\detectfoot_linux\\detectfoot_linux.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\workspace_Vivado2015.1\\detectfoot_linux\\detectfoot_linux.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
